### ISSUE TITLE
LDAP bind failed: "Can't contact LDAP server"

### ISSUE THREAD

**Issue by landmorew** [mricon/totp-cgi#29]
Trying to use this doc to setup totpcgi with google authenticator. 

http://vcdxorbust.com/totpcgi-and-freeradius-with-vmware-view/

Just about there but when I get to the point of generating the QR code on the totpcgi server I get the error above. When I tail the log it shows:

Feb 13 19:03:17 centos64 provisioning.cgi[13597]: Failure: user=administrator@home.local, host=192.168.198.1, message=LDAP bind failed: {'desc': "Can't contact LDAP server"}

LDAP appears to be working though because if I use something like "kinit administrator" it will connect with the same user and password and then show the session info. I can also login to the totpcgi box with the same LDAP account (administrator) successfully.

The part of that error though shows 172.16.198.1 in the message and that's not even a valid machine. The totpcgi machine is 172.16.198.234 and the LDAP is 172.16.198.150. Is there something else I have to do in regards to that provisioning.cgi to get it to point to the right LDAP?

**Comment by landmorew** [comment]
Doesn't appear to be anything wrong with binding to AD either. I just tried:

ldapsearch -x -D "administrator@home.local" -b "cn=Users,dc=home,dc=local" -H ldaps://ad.home.local -W sAMAccountName=administrator

and that spits out all the information.

Just can't figure out why the totpcgi isn't working the same way.

**Comment by mricon** [comment]
Sorry, we can't troubleshoot server configuration issues.

**Comment by landmorew** [comment]
wow, good group here. You write it off to a 'server issue' and close it. Hope your day gets better from here because you must have been having a bad one 3 hours ago. :)

**Comment by tykeal** [comment]
That's because it _is_ a server / configuration issue. We've been down this road several times with folks and every single time it's been a configuration or server issue. The documentation we have provided is very exact in what you need to have configured. Please re-read it, relying on third-party write-ups, and that one in particular seems to cause people a lot of problems. I'm not knocking them for their write-up but almost every person that comes to use because of an issue points at that article.

We _can't_ help you trouble shoot an AD issue, we don't run AD in any of our environments we run OpenLDAP and FreeIPA exclusively.

**Comment by landmorew** [comment]
Sure, I can appreciate that. The reason that it didn't seem to be an AD issue is because I was connecting with it via ldapsearch as you can see above. AD seems to be responding the way it should but when it is going through the totpcgi portion it does not behave the same way.
